pluginManagement {
  plugins {
    id 'biz.aQute.bnd.workspace' version bnd_version
  }
  repositories {
    gradlePluginPortal()
    mavenCentral()
    
    maven {
      url = uri("https://bndtools.jfrog.io/bndtools/libs-release")
    }
  }
}

plugins {
  id 'org.gradle.toolchains.foojay-resolver-convention' version '0.9.0'
  id 'biz.aQute.bnd.workspace'
}